version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    expose:
      - 27017

  books:
    image: mybooks:latest
    build: ./Books
    restart: always
    container_name: books
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongo:27017/
    ports:
      - "5001:5001"
    expose:
      - 5001
