name: assignment3

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log start time
        run: echo "$(date -Iminutes)" > log.txt

      - name: Log submitter names
        run: echo "Shahar kronenfeld and Aviv sharon" >> log.txt

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        id: build
        run: |
            docker buildx build --platform linux/amd64 -t mybooks:latest --load ./Books
            if [ $? -eq 0 ]; then
              echo "image successfully built" >> log.txt
            else
              echo "image not able to be built" >> log.txt
              exit 1
            fi

      - name: Upload log file after build
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: log-file
          path: log.txt



